- DESCRIPTION
- NEWS.md
- R/flywire.R
- tests/testthat/test-flywire.R
> Updated for handling NaNs

- .travis.yml
- DESCRIPTION
- README.md
- _pkgdown.yml
- man/fafbseg-package.Rd
> Updated for #19

- vignettes/articles/FAFB-FlyWire.Rmd
plotly seemed unhappy with shade3d
> switch back to wire3d

- R/flywire-api.R
- man/flywire_xyz2id.Rd
* from ~2-3 points / second to 200 /second in my tests
> Use spine for xyz->supervoxel id mapping

- R/choose-segmentation.R
- R/ids.R
- man/choose_segmentation.Rd
- tests/testthat/test-ids.R
> Feature ffn1-202004

- R/flywire-skeleton.R
* More informative when things go wrong
> Return errors as warning with tryCatch

- .travis.yml
* AFAICS this just duplicates build rebuilding all dependencies
* also not sure if the cache is working in the two steps as doesn't seem to use the stuff
that was built during the precache stage
> remove two stage travis test as seems to duplicate build

- R/autosyn.R
- tests/testthat/test-autosyn.R
> fix flywire_partner_summary when neurons have no synapses

- R/autosyn.R
- tests/testthat/test-autosyn.R
* fix associated tests
* of course should actually implement these details for spine
> Warn when trying to fetch synapse details from spine

- R/flywire-skeleton.R
- tests/testthat/test-skeleton.R
Support single node catmaid neurons in fafb14_to_flywire_ids
@YijieYin
> Handle 1 node neurons

- README.md
Publication date changed between preprint and journal publication.
> Update Buhmann ref date

- R/autosyn.R
- R/choose-segmentation.R
- R/flywire-api.R
- R/flywire-coord.R
- docs/reference/flywire_xyz2id.html
- docs/reference/ngl_layers.html
- inst/flywire-annotations.json
- man/flywire_xyz2id.Rd
- tests/testthat/test-ids.R
Update of hostname used for services hosted on spine.
~~TODO: Update hostname for static file serving (brain meshes).~~
Should be good to go.
> spine.janelia.org -> services.itanna.io

- R/flywire-coord.R
- tests/testthat/test-flywire.R
> make flywire_raw2nm() use vox dims if supplied

- .github/workflows/R-CMD-check.yaml
- R/autosyn.R
- R/flytable.R
- R/flywire-api.R
- R/flywire-arrow.R
- R/flywire-urls.R
- R/utils.R
- man/flywire_connectome_data.Rd
- man/flywire_ids.Rd
- tests/testthat/test-autosyn.R
- tests/testthat/test-flytable.R
- tests/testthat/test-flywire-arrow.R
- tests/testthat/test-flywire.R
Some issues that have come up with dependency and dataset changes
> Fix fafbseg inner_join / tests

- R/autosyn.R
- R/flywire-arrow.R
- man/flywire_partners.Rd
* but still no support for flywire_partners
> flywire_partner_summary: support versions/timestamps

- .github/workflows/R-CMD-check.yaml
* hoping that sys reqs will get sorted out by pak
* need to check if macosx brew hdf5 install required
> simplify install on github

- R/flytable.R
* switching to non-memoised inside a memoised fn isn't going to work
> fix stale flytable base cache

- R/flywire-arrow.R
- man/flywire_connectome_data.Rd
* I am not sure if the set=FALSE option is a good idea but probably harmless
> Respect user selected data version

- R/utils.R
- man/simple_python.Rd
* navis+fafbseg-py is quite useful but a bit fiddlier to install
* meshparty is a real pain to install
* therefore now have "full" for fafbseg and "extra" for meshparty et al
> give simple_python extra option for meshparty et al

- R/autosyn.R
- R/flytable.R
- R/flywire-arrow.R
- R/release-data.R
- R/utils.R
- README.md
- man/download_flywire_release_data.Rd
- man/flywire_connectome_data.Rd
- man/flywire_sirepo_file.Rd
- tests/testthat/test-flywire-arrow.R
- tests/testthat/test-sirepo.R
- tests/testthat/test-utils.R
- vignettes/fafbseg-catmaid-legacy-info.Rmd
* includes support for annotations released with Schlegel et al 2023 revision
* and corresponding connectivity data
> support for materialisation 783 artefacts

- R/fafbseg-py.R
* new way to set up default datastack
* new function names for L2 skels/dotprops
* see  #193
> changes for fafbseg-py v3

- .github/workflows/R-CMD-check.yaml
- R/flywire-urls.R
- R/utils.R
- tests/testthat/test-urls.R
* also coconat keys (fw:xxx) but that can be a surprise for now
> teach flywire_ids to accept any whitespace

- R/release-data.R
- man/flywire_sirepo_file.Rd
- tests/testthat/test-release-data.R
* needed by neck connectome paper
* also fixes a git credential issue
> Support for generic si git repositories

- R/ng-scene.R
- tests/testthat/test-ng-scene.R
> teach xform.ngscene to support multisource layers
